JWT = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkxNTkyNzd9.lSBcERDcy3F0J1aY4VbCD9wowcK36cM0Wpos4mQbeZE

### USERS REQUESTS ###
 ## SIGNUP ##
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Joey",
  "last_name": "Black",
  "email": "joe@test.com",
  "password": "password",
  "password_conformation": "password"
}

### SESSIONS REQUESTS ###
  ## LOGIN ##
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "joe@test.com",
  "password": "password"
}

### CAMPGROUND REQUESTS ###

GET http://localhost:3000/campgrounds
Content-Type: application/json

Get http://localhost:3000/campgrounds/1200

### CREATE ###
POST http://localhost:3000/campgrounds
Content-Type: application/json

{
  "lon": 1.0,
  "lat": 2.0,
  "gps_composite_field": "some gps field",
  "campground_code": "123",
  "campground_name": "Test Campground",
  "campground_type": "tent",
  "phone_number": "123-456-7890",
  "dates_open": "May - September",
  "comments": "some comments",
  "number_of_campsites": 10,
  "elevation": 1000,
  "amenities": "fire pits",
  "state": "CA",
  "nearest_town": "some town"
}

### UPDATE ###
PATCH http://localhost:3000/campgrounds/1200
Content-Type: application/json

{
  "gps_composite_field": "some gps field"
}